### ISSUE TITLE
isClose() on IDLE connection throws SQLException - Flyway is using isClosed()

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-datasource#65]
Refer: https://groups.google.com/g/ebean/c/RrAXwteNU3k

Should I be concerned with this error while running Flyway migration?
```
java.sql.SQLException: Pooled Connection has been accessed whilst idle in the pool, via method: isClosed()
    at io.ebean.datasource.pool.PooledConnection.isClosed(PooledConnection.java:607) ~[ebean-datasource-8.2.jar:8.2]
    at org.flywaydb.core.internal.jdbc.JdbcUtils.closeConnection(JdbcUtils.java:98) ~[flyway-core-8.5.13.jar:na]
    at org.flywaydb.core.internal.database.base.Database.close(Database.java:386) ~[flyway-core-8.5.13.jar:na]
    at org.flywaydb.core.internal.util.IOUtils.close(IOUtils.java:34) ~[flyway-core-8.5.13.jar:na]
    at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:214) ~[flyway-core-8.5.13.jar:na]
    at org.flywaydb.core.Flyway.migrate(Flyway.java:124) ~[flyway-core-8.5.13.jar:na]
```
Flyway appeared to call connection.close() twice in the org.flywaydb.core.internal.database.base class:

```java
public void close() {
  if (!useSingleConnection() && migrationConnection != null) {
    migrationConnection.close();
  }
  if (mainConnection != null) {
    mainConnection.close();
  }

  if (rawMainJdbcConnection != null) {
    JdbcUtils.closeConnection(rawMainJdbcConnection);
  }
}
```

**Comment by rbygrave** [comment]
> Should I be concerned with this error while running Flyway migration?

It does look harmless with the try catch occurring in JdbcUtils.closeConnection() ... but we can and should fix this in the PooledConnection.isClosed() implementation with  if (status == STATUS_IDLE) return true; // I'm a connection back in the pool so closed = true

... noting that Flyway have effectively got a race condition here.  The second attempt to close is using isClosed() which is going to be a race condition against something else (some other thread) acquiring that same connection from the pool. It might well be fine as it is super close to the other close() invocation plus generally during migration running there is nothing else allowed to execute until after migrations have completed. It's extremely unlikely that another thread is going to acquire the connection (but not impossible).
 
Cheers, Rob.
